<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category_id' => 1,
                'name' => 'Hydrating Face Serum',
                'slug' => 'hydrating-face-serum',
                'description' => 'Intensive hydrating serum with hyaluronic acid for plump, dewy skin.',
                'short_description' => 'Deep hydration for radiant skin',
                'price' => 2500,
                'sale_price' => 1999,
                'sku' => 'SKU-001',
                'stock_quantity' => 50,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Beauty',
            ],
            [
                'category_id' => 1,
                'name' => 'Vitamin C Brightening Cream',
                'slug' => 'vitamin-c-brightening-cream',
                'description' => 'Enriched with vitamin C and antioxidants for radiant, even-toned skin.',
                'short_description' => 'Brighten and even skin tone',
                'price' => 3200,
                'sale_price' => null,
                'sku' => 'SKU-002',
                'stock_quantity' => 35,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Beauty',
            ],
            [
                'category_id' => 1,
                'name' => 'Anti-Aging Night Cream',
                'slug' => 'anti-aging-night-cream',
                'description' => 'Rich night cream with retinol and peptides to reduce fine lines.',
                'short_description' => 'Wake up to younger-looking skin',
                'price' => 4500,
                'sale_price' => 3800,
                'sku' => 'SKU-003',
                'stock_quantity' => 25,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Premium',
            ],
            [
                'category_id' => 2,
                'name' => 'Velvet Matte Lipstick',
                'slug' => 'velvet-matte-lipstick',
                'description' => 'Long-lasting matte lipstick with intense color payoff.',
                'short_description' => 'Bold color that lasts all day',
                'price' => 1200,
                'sale_price' => null,
                'sku' => 'SKU-004',
                'stock_quantity' => 100,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Color',
            ],
            [
                'category_id' => 2,
                'name' => 'Volumizing Mascara',
                'slug' => 'volumizing-mascara',
                'description' => 'Buildable volume mascara for dramatic, dramatic lashes.',
                'short_description' => 'Dramatic volume for your lashes',
                'price' => 950,
                'sale_price' => 750,
                'sku' => 'SKU-005',
                'stock_quantity' => 80,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Color',
            ],
            [
                'category_id' => 2,
                'name' => 'Foundation - Natural Glow',
                'slug' => 'foundation-natural-glow',
                'description' => 'Lightweight foundation with buildable coverage and natural finish.',
                'short_description' => 'Buildable coverage, natural finish',
                'price' => 2800,
                'sale_price' => null,
                'sku' => 'SKU-006',
                'stock_quantity' => 45,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Color',
            ],
            [
                'category_id' => 3,
                'name' => 'Rose Petal Perfume',
                'slug' => 'rose-petal-perfume',
                'description' => 'Exquisite floral fragrance with notes of rose and jasmine.',
                'short_description' => 'Timeless floral elegance',
                'price' => 5500,
                'sale_price' => 4500,
                'sku' => 'SKU-007',
                'stock_quantity' => 20,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Fragrance',
            ],
            [
                'category_id' => 3,
                'name' => 'Vanilla Dream Eau de Parfum',
                'slug' => 'vanilla-dream-eau-de-parfum',
                'description' => 'Warm vanilla with hints of amber and sandalwood.',
                'short_description' => 'Warm and sensual vanilla scent',
                'price' => 4800,
                'sale_price' => null,
                'sku' => 'SKU-008',
                'stock_quantity' => 30,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Fragrance',
            ],
            [
                'category_id' => 4,
                'name' => 'Argan Hair Oil',
                'slug' => 'argan-hair-oil',
                'description' => 'Pure argan oil for shiny, frizz-free hair.',
                'short_description' => 'Nourish and shine',
                'price' => 1800,
                'sale_price' => 1500,
                'sku' => 'SKU-009',
                'stock_quantity' => 60,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Hair',
            ],
            [
                'category_id' => 5,
                'name' => 'Luxury Bath Bomb Set',
                'slug' => 'luxury-bath-bomb-set',
                'description' => 'Set of 6 fizzing bath bombs with essential oils.',
                'short_description' => 'Relaxing bath time luxury',
                'price' => 2200,
                'sale_price' => null,
                'sku' => 'SKU-010',
                'stock_quantity' => 40,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Bath',
            ],
            [
                'category_id' => 1,
                'name' => 'Gentle Foam Cleanser',
                'slug' => 'gentle-foam-cleanser',
                'description' => 'pH balanced foam cleanser for all skin types.',
                'short_description' => 'Gentle daily cleanse',
                'price' => 850,
                'sale_price' => 650,
                'sku' => 'SKU-011',
                'stock_quantity' => 75,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Beauty',
            ],
            [
                'category_id' => 1,
                'name' => 'Hydrating Toner',
                'slug' => 'hydrating-toner',
                'description' => 'Alcohol-free hydrating toner for soft skin.',
                'short_description' => 'Prep and hydrate',
                'price' => 1100,
                'sale_price' => null,
                'sku' => 'SKU-012',
                'stock_quantity' => 55,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Beauty',
            ],
            [
                'category_id' => 2,
                'name' => ' eyeliner Gel',
                'slug' => 'eyeliner-gel',
                'description' => 'Long-wear gel eyeliner for precise application.',
                'short_description' => 'Precision eyeliner',
                'price' => 750,
                'sale_price' => 599,
                'sku' => 'SKU-013',
                'stock_quantity' => 90,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Color',
            ],
            [
                'category_id' => 2,
                'name' => 'Blush On - Rose',
                'slug' => 'blush-on-rose',
                'description' => 'Silky powder blush for a natural flush.',
                'short_description' => 'Natural rose flush',
                'price' => 890,
                'sale_price' => null,
                'sku' => 'SKU-014',
                'stock_quantity' => 65,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Color',
            ],
            [
                'category_id' => 3,
                'name' => 'Fresh Cotton Perfume',
                'slug' => 'fresh-cotton-perfume',
                'description' => 'Clean cotton scent with citrus notes.',
                'short_description' => 'Fresh and clean',
                'price' => 3200,
                'sale_price' => 2800,
                'sku' => 'SKU-015',
                'stock_quantity' => 25,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Fragrance',
            ],
            [
                'category_id' => 4,
                'name' => 'Hair Serum',
                'slug' => 'hair-serum',
                'description' => 'Lightweight hair serum for shine and smoothness.',
                'short_description' => 'Smooth and shiny',
                'price' => 950,
                'sale_price' => null,
                'sku' => 'SKU-016',
                'stock_quantity' => 50,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Hair',
            ],
            [
                'category_id' => 5,
                'name' => 'Body Lotion',
                'slug' => 'body-lotion',
                'description' => 'Moisturizing body lotion with shea butter.',
                'short_description' => 'Deep moisturization',
                'price' => 1200,
                'sale_price' => 999,
                'sku' => 'SKU-017',
                'stock_quantity' => 40,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Bath',
            ],
            [
                'category_id' => 1,
                'name' => 'Eye Cream',
                'slug' => 'eye-cream',
                'description' => 'Revitalizing eye cream for dark circles.',
                'short_description' => 'Brighten under eyes',
                'price' => 1800,
                'sale_price' => null,
                'sku' => 'SKU-018',
                'stock_quantity' => 30,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Beauty',
            ],
            [
                'category_id' => 2,
                'name' => 'Lip Gloss',
                'slug' => 'lip-gloss',
                'description' => 'Shiny lip gloss with vitamin E.',
                'short_description' => 'Glossy lips',
                'price' => 550,
                'sale_price' => 450,
                'sku' => 'SKU-019',
                'stock_quantity' => 120,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Color',
            ],
            [
                'category_id' => 3,
                'name' => 'Musk Perfume',
                'slug' => 'musk-perfume',
                'description' => 'Sensual musk fragrance with floral notes.',
                'short_description' => 'Sensual musk',
                'price' => 4200,
                'sale_price' => null,
                'sku' => 'SKU-020',
                'stock_quantity' => 15,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Fragrance',
            ],
            [
                'category_id' => 4,
                'name' => 'Shampoo',
                'slug' => 'shampoo',
                'description' => 'Gentle shampoo for all hair types.',
                'short_description' => 'Clean and soft',
                'price' => 650,
                'sale_price' => 499,
                'sku' => 'SKU-021',
                'stock_quantity' => 80,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Hair',
            ],
            [
                'category_id' => 5,
                'name' => 'Body Scrub',
                'slug' => 'body-scrub',
                'description' => 'Exfoliating body scrub with natural ingredients.',
                'short_description' => 'Smooth skin',
                'price' => 1500,
                'sale_price' => null,
                'sku' => 'SKU-022',
                'stock_quantity' => 35,
                'is_featured' => false,
                'is_active' => true,
                'brand' => 'Shirin Bath',
            ],
            [
                'category_id' => 1,
                'name' => 'Sheet Mask Set',
                'slug' => 'sheet-mask-set',
                'description' => 'Set of 10 hydrating sheet masks.',
                'short_description' => 'Weekly hydration',
                'price' => 2000,
                'sale_price' => 1600,
                'sku' => 'SKU-023',
                'stock_quantity' => 45,
                'is_featured' => true,
                'is_active' => true,
                'brand' => 'Shirin Beauty',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
